### ISSUE TITLE
question in smartcore/src/svm/svr.rs?

### ISSUE THREAD

**Issue by z1queue** [smartcorelib/smartcore#105]
in smartcore/src/svm/svr.rs
line 311:     gmin: T::max_value(),
line 312:     gmax: T::min_value(),

it looks like the gmin and gmax values are reversed.

it should be like this:
line 311:     gmin: T::min_value(),
line 312:     gmax: T::max_value(),?

**Comment by VolodymyrOrlov** [comment]
@z1queue the initial values for `gmin ` and `gmax ` are intentionally set to global max and min. Otherwise the values will never be minimized later.
