### ISSUE TITLE
fill out the Apache license

### ISSUE THREAD

**Issue by pmarks** [smartcorelib/smartcore#114]
The LICENSE file doesn't have a year & copyright holder filled in: https://github.com/smartcorelib/smartcore/blob/development/LICENSE#L189

This can cause an issue with a legal review of dependencies, because it can be interpreted to mean that the package wasn't "really" put under that license. 

Thanks!

**Comment by Mec-iS** [comment]
sorry about that. I will ping @VolodymyrOrlov about this
