### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by mlondschien** [smartcorelib/smartcore#122]
Is there any release planned for `smartcore`? I have a crate `changeforest` that depends on the latest commits implementing seeded & oob random forests and would like to publish this to crates.io. A release of `smartcore=0.3.0` would help a lot.

**Comment by cmccomb** [comment]
I'd love to see a new release too! Seems like there are some significantly useful commits since 0.2.0.

**Comment by cmccomb** [comment]
@VolodymyrOrlov @morenol thoughts?

**Comment by morenol** [comment]
I don't have permissions in crates.io, I'll try to contact Vlad for the release

**Comment by morenol** [comment]
Release done!
