### ISSUE TITLE
Naive Bayes (NB) Classifier

### ISSUE THREAD

**Issue by VolodymyrOrlov** [smartcorelib/smartcore#14]
Implement Base NB classifier that doesn't make any assumptions about the underlying distribution of **x**. 

https://scikit-learn.org/stable/modules/naive_bayes.html

We need something like this (pseudocode):

```
trait NBDistribution:
    
    // Fit distribution to some continuous or discrete data
    def fit(x: Matrix<T>) -> NBDistribution
    
    // prior of class k 
    def prior(k) -> T

    // conditional probability of feature j give class k
    def conditional_probability(k, j)-> T

class BaseNaiveBayes:
    
    // "Fits" NB. This method validates and remembers parameters
    def fit(distribution: NBDistribution)
    
    // Calculates likelihood of labels using stored probabilities and X. Returns vector with estimated labels
    def predict(x: Matrix<T>) -> Vector<T>
```

Once we have `BaseNaiveBayes` we can implement Gaussian Naive Bayes, Multinomial Naive Bayes and Bernoulli Naive Bayes as concrete implementations of trait `NBDistribution`

**Comment by morenol** [comment]
Remaining NB classifiers to implement:

-[ ] [Multinomial Naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html#multinomial-naive-bayes)
-[ ] [Complement Naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html#complement-naive-bayes)
-[ ] [Bernoulli Naive Bayes](https://scikit-learn.org/stable/modules/naive_bayes.html#bernoulli-naive-bayes)

And also a partial_fit()  for the cases where it makes sense, right? @VolodymyrOrlov

**Comment by VolodymyrOrlov** [comment]
@morenol can I close this issue, or would you like to keep it open until `Complement Naive Bayes` is implemented?

**Comment by morenol** [comment]
I think that we should close this when the documentation is already in the code.
