### ISSUE TITLE
LogisticRegression infinite loop

### ISSUE THREAD

**Issue by levkk** [smartcorelib/smartcore#149]
When training on a dataset that has too many classes, e.g. Scikit's [diabetes](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html), `smartcore::linear::logistic_regression::LogisticRegression` runs into an infinite loop.

Reproducible example attached.

[main.rs.txt](https://github.com/smartcorelib/smartcore/files/9523201/main.rs.txt)

**Comment by Mec-iS** [comment]
Thanks for your report.

Looks like there is a problem with [this call](https://github.com/smartcorelib/smartcore/blob/e445f0d558319b282e9846ff575c22f1c83e73ea/src/linear/logistic_regression.rs#L375):

```
let result = LogisticRegression::minimize(x0, objective);
```

**Comment by Mec-iS** [comment]
Looks like this is not a bug, the particular computation just takes a lot of time in a single-CPU configuration to compute [this loop](https://github.com/smartcorelib/smartcore/blob/820201e92079aa70f71ee780f504cc72817c6b60/src/optimization/first_order/lbfgs.rs#L216)

How long does it takes with a Python library?

**Comment by levkk** [comment]
Less than a second:

```
time python main.py 
[200.]

real	0m0.390s
user	0m0.592s
sys	0m0.878s
```

Code attached (sorry, long file because formatting).

[main.py.txt](https://github.com/smartcorelib/smartcore/files/9550450/main.py.txt)

**Comment by Mec-iS** [comment]
The loop stops only after the limit of 1000 iterations is reached, so I suppose the algorithm is not doing its job correctly.
Could you confirm that this results are correct please:
```
lr.coefficients().shape() -> (214, 10)
lr.intercept().shape() -> (214, 1)
lr.coefficients().get(0, 0) -> 10.926448436791203
lr.intercept().get(0, 0) -> 20.061156556933966
```

**Comment by Mec-iS** [comment]
This works with the new branch `v0.5-wip`, it is still a little slow but much better.

Probably we should move this into something `Optimize Linear Regression performance`

**Comment by Mec-iS** [comment]
@levkk you can see your example working at https://github.com/smartcorelib/smartcore-jupyter/blob/main/notebooks/99-Test.ipynb
