### ISSUE TITLE
Make compatible with  non-browser wasm targets

### ISSUE THREAD

**Issue by morenol** [smartcorelib/smartcore#162]
Currently, smartcore works in browser clients through the wasm-unknown-unknown target. It would be great if we could target smartcore in WASM outside of the browser world (wasmtime, wasmer...etc)

**Comment by Mec-iS** [comment]
what about `wasm-unknown-wasi`?

**Comment by morenol** [comment]
Yes, I think that making sure that we can build and use that target is a good first step. But in particular I also would love to be able to use wasm-unknown-unknown in wasmtime runtine because that is good for a use case that I want to try.
