### ISSUE TITLE
Allow JSON construction of params

### ISSUE THREAD

**Issue by montanalow** [smartcorelib/smartcore#165]
PostgresML instantiates algorithm params from JSON passed in at runtime. This isn't quite the same as serde deserialization, since the JSON params may be incomplete, and the missing ones will be filled in by Default::default(). We're currently adding this functionality downstream, but wondered if you'd be interested in adopting this upstream as well.

An example is in this PR https://github.com/postgresml/postgresml/pull/332/files#diff-a1bcda73e2901512a661eebf9e868be4f33dd99ac4952a85957397a860ec2035

**Comment by montanalow** [comment]
I think it could be cleaner and easier to maintain here, by adopting `#[serde(default)]` on structs, if this functionality would be more broadly useful.

**Comment by morenol** [comment]
> I think it could be cleaner and easier to maintain here, by adopting `#[serde(default)]` on structs, if this functionality would be more broadly useful.

I agree, I think that we can use `#[serde(default)]` 

I am in for this!

**Comment by morenol** [comment]
Can we close this now, right? @montanalow
