### ISSUE TITLE
Add cargo clippy checks

### ISSUE THREAD

**Issue by morenol** [smartcorelib/smartcore#22]
Fix [cargo clippy](https://github.com/rust-lang/rust-clippy) warnings and add to the CI something that checks for that.

 There is a [cargo clippy --fix](https://github.com/rust-lang/rust-clippy#automatically-applying-clippy-suggestions) command that can solve some of the warnings, that could be used at the beginning.

The instructions to run cargo clippy are:

```
rustup component add clippy # to install it
cargo clippy
```

**Comment by VolodymyrOrlov** [comment]
@morenol I am going to close this issue since you have covered most basic checks. Let me know if you want to keep it open.

**Comment by morenol** [comment]
These are the warning that we are ignoring right now in lib.rs
- [ ] clippy::needless_range_loop,
- [ ] clippy::ptr_arg,
- [ ] clippy::type_complexity,
- [ ] clippy::too_many_arguments,
- [ ] clippy::many_single_char_names

What do you think about them?  Maybe we can move that from lib.rs to the specific places where we have those lint errors and while doing that we can fix some of them, so far I have a branch all the places where clippy::needless_range_loop is happening but not sure if we should fix them or just ignore them.

**Comment by VolodymyrOrlov** [comment]
I think ignoring these warning is fine for now. From my point of view a lot of these problems can be ignored, like `many_single_char_names ` or `too_many_arguments ` since these problems will not lead to ineffective code or runtime crash. 
In my opinion, only `needless_range_loop ` and `ptr_arg ` deserve to be fixed.

**Comment by morenol** [comment]
perfect, then I will fix them. I also fixed some of the places where ptr_arg was appearing, I will create a PR with that
