### ISSUE TITLE
Deserialization for Kernel

### ISSUE THREAD

**Issue by Mec-iS** [smartcorelib/smartcore#221]
`Kernel` is now an object-safe trait so we can use its type as `&dyn Kernel`, it has also a `name()` function to have a string representation of the kernel as `LinearKernel`, `RBFKernel`, ...

We would like to provide a functionality that instantiate the kernel's default from a string:
```
"LinearKernel" -> LinearKernel::Default()
```
via a enum
```
pub enum KernelName {
    Linear(LinearKernel),
   ...
}
```
This possibility is known to be not possible in vanilla Rust but there is a library that provides it, see [blogpost](https://fdeantoni.medium.com/rust-and-dynamically-loading-structs-c311d8edbef6).

This feature should be only available and loaded in pairing with the "serde" feature so to avoid adding another library to the deps.

This will allow parameters that contain `pub kernel: Option<&'a dyn Kernel<'a>>,` to be deserializable.

**Comment by morenol** [comment]
I can take this, I think that we can get ride of `name` in Kernel trait, and instead handle that in the enum

**Comment by Mec-iS** [comment]
ok, the problem with Rust comes when is needed to go string->instance. there is no easy way like in Python `getattr(module, string)` to read an object from a string.
