### ISSUE TITLE
Comparison with linfa

### ISSUE THREAD

**Issue by wangjiawen2013** [smartcorelib/smartcore#277]
Hi,
It seems like some main functions between smartcore and linfa are overlapping, what's the differences between them ?

**Comment by Mec-iS** [comment]
Some of the differences in design principles between the two libraries are written in this comment: https://github.com/smartcorelib/smartcore/pull/257#issuecomment-1499886875
briefly, smartcore does not target ML practioners (like `polars` or `linfa`) but the use on embedded devices, edge devices or the browser, or embedding in high performance applications.
