### ISSUE TITLE
Add predict_proba method for LogisticRegression

### ISSUE THREAD

**Issue by geosarr** [smartcorelib/smartcore#278]
### I'm submitting a 
- [ ] bug report.
- [ ] improvement.
- [x] feature request.

### Current Behaviour:
Hi, the struct LogisticRegression does not have a method that directly returns the estimated probabilities.

### Expected Behaviour:
It will be great to add a predict_proba method like (https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html), in order to account for unbalanced datasets.

### Do you want to work on this issue?
yes.

**Comment by Mec-iS** [comment]
Hey, thanks for your interest.
Please run a search before opening issues as this is currently already addressed and there is also a PR open that needs some additional working if you want to contribute:

https://github.com/smartcorelib/smartcore/issues/50
https://github.com/smartcorelib/smartcore/pull/211
