### ISSUE TITLE
Release Timeline

### ISSUE THREAD

**Issue by nishaq503** [smartcorelib/smartcore#282]
Hello,

I'm wondering when there will be a release of version `0.4` of `smartcore` to `crates.io`. I'm using the version from the `development` branch in one of my crates and the git dependency is blocking me from publishing. I'm sure there are other developers who are also waiting. Is there a timeline for publishing `smartcore`?

Thanks

**Comment by morenol** [comment]
I can create a new release, but I would like to fix all the clippy issues first

**Comment by morenol** [comment]
@Mec-iS I fixed the clippy issues, is there anything that comes to your mind that we would like to have before a new release?

**Comment by Mec-iS** [comment]
if the code in the branch is been used I don't see any problem in releasing

**Comment by morenol** [comment]
crate released
