### ISSUE TITLE
Implement StandardScaler

### ISSUE THREAD

**Issue by VolodymyrOrlov** [smartcorelib/smartcore#54]
StandardScaler standardizes features by removing the mean and scaling to unit variance. Implementation details and parameters can be found in [Scikit Learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html). 

The algorithm should be implemented as a struct that extends [`Transformer`](https://github.com/smartcorelib/smartcore/blob/development/src/api.rs#L39). The struct should belong to a new module `preprocessing`

**Comment by Mec-iS** [comment]
I have done some work with scalers recently. So I can pick this up.

**Comment by titoeb** [comment]
@Mec-iS: I had a look at this issue in my vacation and it resulted in this PR #143, feel free to comment and bring in the ideas you had in mind.
